version: '3.6'
services:
    nginx:
        image: nginx:1.19.3-alpine
        restart: always
        volumes:
            # config and logs
            - ./data/nginx/conf:/etc/nginx/conf.d:ro
            - ./data/nginx/log:/var/log/nginx
            # static page
            - ./landing:/var/www/landing:ro
            # SSL params and certs
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        # reload certificates every six hours
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        restart: always
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        # check for certificate renewal every 12 hours
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
