version: '3'
services:
    postgres_backend:
        image: postgres:12.2-alpine
        volumes:
            - ./data/postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=docker
        ports:
            - 5432:5432

    uwsgi_flask_backend:
        image: sgasse/uwsgi_flask_backend
        build:
            context: uwsgi_flask_backend
        depends_on:
            - postgres_backend

    nginx_frontend:
        image: nginx:1.13-alpine
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - uwsgi_flask_backend
        ports:
            - 80:80